export const skillsIcons = [
  "Javascript",
  "HTML5",
  "CSS",
  "React",
  "React Router",
  "Redux",
  "Next.js",
  "TypeScript",
  "Vite",
  "SASS/SCSS",
  "TailwindCSS",
  "HeadlessUI",
  "Firebase",
  "Supabase",
  "Github",
];
export const projectsData = [
  {
    id: 0,
    title: "PolyTech",
    text: "This website was created as part of my diploma project, leveraging cutting-edge technologies like Next.js, React, Redux, and TypeScript. The website serves as a marketplace platform where users can browse and purchase products, manage their carts, and maintain personalized profiles. All user data and transactions are handled efficiently with Redux for state management, while TypeScript ensures code reliability. The project incorporates Tailwind CSS for responsive and modern styling, and Vite for optimized performance. Additionally, the platform features smooth navigation and basic security measures, with plans to integrate payment processing and further enhance user experience in future iterations.",
    tags: ["Next.js", "Typescript", "React", "Tailwind", "Supabase"],
    images: ["PolyTech-1.webp", "PolyTech-2.webp", "PolyTech-3.webp", "PolyTech-4.webp"],
    link: "https://github.com/YuraRR/marketplace-for-diploma",
  },
  {
    id: 1,
    title: "Mindori",
    text: "This project involved using the new technologies like React Router and Firebase. The website allows users to view vacation rental properties, search for available dates, and book selected houses and additional services. All bookings are stored in Firebase, and once a booking is made, the property becomes unavailable for future searches on those dates. Additionally, users can receive a discount certificate via email after a simulated payment, facilitated by EmailJS. The project also incorporated various libraries for animations, smooth page transitions, and form validation.",
    tags: ["React", "Redux", "React Router", "Tailwind", "Firebase"],
    images: ["Mindori-1.webp", "Mindori-2.webp", "Mindori-3.webp", "Mindori-4.webp"],
    link: "https://github.com/YuraRR/Mindori",
  },
  {
    id: 2,
    title: "Simple Factory",
    text: "This JavaScript game is my largest project to date, taking around six months to develop. Simple Factory features isometric 2D graphics created without engines or libraries. Most visual content, such as factory models and items, was designed by me using MagicaVoxel. The game focuses on automating processes like mining resources, transporting them via conveyor belts or vehicles, and gradually processing and converting them into finished products. It includes about 50 different materials and products, as well as numerous factories and plants for resource extraction and processing. Throughout development, I encountered many serious challenges, which greatly enhanced my JavaScript skills",
    tags: ["JavaScript", "SCSS"],
    images: [
      "Simple-factory-1.webp",
      "Simple-factory-2.webp",
      "Simple-factory-3.webp",
      "Simple-factory-4.webp",
      "Simple-factory-5.webp",
    ],
    link: "https://github.com/YuraRR/Simple-Factory",
  },
  {
    id: 3,
    title: "WR-SR Calculator",
    text: "This small project was created to practice React and Tailwind. The calculator is designed for computing data from the city-building game Workers & Resources: Soviet Republic, such as energy, water, and heating values needed for the proper functioning of selected residential buildings. It also displays the number of required buildings and infrastructure, such as power plants, wires, pipes, etc., to provide these services.",
    tags: ["React", "Tailwind"],
    images: ["WR-SR-Calculator-1.webp", "WR-SR-Calculator-2.webp"],
    link: "https://github.com/YuraRR/WR-SR-Calculator",
  },
  {
    id: 4,
    title: "CutSpace",
    text: "Cutspace Project is a basic landing page I created during the early stages of my JavaScript learning. It has a simple, modern design based on a Figma mockup. The site doesn’t use any extra libraries and was built using just HTML, CSS, and JavaScript. This project shows my ability to turn design ideas into real, functional web pages while practicing my core skills.",
    tags: ["JavaScript", "CSS"],
    images: ["CutSpace-1.webp", "CutSpace-2.webp", "CutSpace-3.webp"],
    link: "",
  },
  {
    id: 5,
    title: "GD-Consulting",
    text: "GD-Consulting was my first collaborative project, developed with a friend. It involved creating a multi-page website where we worked together to build a fully functional site based on a Figma mockup. To coordinate our efforts efficiently, we used GitHub for version control and project management.We divided the tasks according to our strengths and started working on different sections of the site simultaneously. This approach allowed us to make steady progress and integrate our work seamlessly. This project provided valuable experience in teamwork, collaboration, and managing a shared codebase, enhancing both my technical skills and my ability to work effectively with others.",
    tags: ["JavaScript", "SCSS"],
    images: ["GD-1.webp", "GD-2.webp", "GD-3.webp"],
    link: "https://github.com/YuraRR/GD-Consulting",
  },
];
