export const skillsIcons = [
  "Javascript",
  "HTML5",
  "CSS",
  "React",
  "React Router",
  "Redux",
  "Vite",
  "SASS/SCSS",
  "TailwindCSS",
  "HeadlessUI",
  "Firebase",
  "Github",
];
export const projectsData = [
  {
    id: 0,
    title: "Mindori",
    text: "Booking website",
    tags: ["React", "Redux", "React Router", "Tailwind", "Firebase"],
    images: ["Mindori-1.png", "Mindori-2.png"],
    link: "https://github.com/YuraRR/Mindori",
  },
  {
    id: 1,
    title: "Simple Factory",
    text: "Game",
    tags: ["JavaScript", "SCSS"],
    images: ["Mindori-1.png", "Mindori-2.png"],
    link: "https://github.com/YuraRR/Simple-Factory",
  },
  {
    id: 2,
    title: "WR-SR Calculator",
    text: "Calculator",
    tags: ["React", "Tailwind"],
    images: ["Mindori-1.png", "Mindori-2.png"],
    link: "https://github.com/YuraRR/WR-SR-Calculator",
  },
  {
    id: 3,
    title: "CutSpace",
    text: "Landing",
    tags: ["JavaScript"],
    images: ["Mindori-1.png", "Mindori-2.png"],
    link: "",
  },
  {
    id: 4,
    title: "GD-Consulting",
    text: "Multipage website",
    tags: ["JavaScript"],
    images: ["Mindori-1.png", "Mindori-2.png"],
    link: "https://github.com/YuraRR/GD-Consulting",
  },
];
